# Generated by Django 4.1.7 on 2023-05-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_item_image_remove_user_address_item_imagepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagePath',
            field=models.CharField(default='f1.jpg', max_length=200),
        ),
    ]
