# Generated by Django 4.1.7 on 2023-05-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_item_imagepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.TextField(blank=True, default='A moist, flavorful, cake with golden raisins, shredded carrots, This cake is filled with a cream cheese filling. We also use this same recipe for our morning glory that has a honey glaze on top instead of the frosting, great for breakfast.', null=True),
        ),
    ]
