# Generated by Django 4.1.7 on 2023-05-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_item_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='imagePath',
            field=models.CharField(default='b1.jpg', max_length=200),
        ),
    ]
