# Generated by Django 4.1.7 on 2023-05-18 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_cartitem_user_alter_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryAddress', models.CharField(max_length=200, null=True)),
                ('items', models.ManyToManyField(blank=True, related_name='items', to='base.cartitem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cart')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
